### ISSUE TITLE
TypeError in eval_metrics Initialization During Execution of eval.py

### ISSUE THREAD

**Issue by aomenfage** [ipc-lab/deepjscc-wz#1]
Hello,

I encountered an error while running a project from this repository. The error occurred when I executed the following command:

`python ./src/eval.py trainer.devices=[1] experiment=wz/wz_eval ckpt_path=./checkpoints/Cityscape_16_DeepJSCCWZ.ckpt`

The error log is as follows:

```
[2024-03-26 10:41:56,204][src.utils.utils][ERROR] -
Traceback (most recent call last):
File "/home/sc/miniconda3/envs/zxy_deepJSCC/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
return target(*args, **kwargs)
File "/mnt/4t/code_space/zxy/deepjscc-wz-main/src/models/wz/deepjscc_wz.py", line 15, in init
super().init(N=N, bw_factor=bw_factor, **kwargs)
File "/mnt/4t/code_space/zxy/deepjscc-wz-main/src/models/base_deepjscc.py", line 34, in init
self.init_metrics()
File "/mnt/4t/code_space/zxy/deepjscc-wz-main/src/models/base_deepjscc.py", line 51, in init_metrics
eval_metrics = CustomMetricCollection({
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
```

It seems like there's a TypeError during the initialization of `eval_metrics` in `base_deepjscc.py`. 

Could you please help in resolving this issue or suggest any workaround?

Thank you!

**Comment by selimfirat** [comment]
Hi! This error seems related to your Python version since the dict union operator was added in 3.9. Please use Python 3.9+, or preferably 3.10.13.
